# frozen_string_literal: true

REPO_FULL_NAME = github.pr_json["base"]["repo"]["full_name"]

PR_LIMIT = 5

WELCOME_MESSAGE = <<~MARKDOWN
# Welcome! :wave:
Hi, @#{github.pr_author}! Thank you for the PR, and your interest
in the otwarchive project.

Please take a moment to visit at these helpful links
* https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/
* https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md

If you'd like the ability to comment on, assign, and transition Jira
issues in the future, you're welcome to create a Jira account!
You can reply here with the account name and we'll set up the permissions
for you. (It makes things a bit easier for us on the organizational side
if the Full Name on your Jira account either matches the name you'd like us
to credit in the release notes or includes it in parentheses,
e.g. "Nickname (PREFERRED NAME).")

Thanks again for contributing! If you have any questions,
you can contact us at otw-coders@transformativeworks.org.
MARKDOWN

# Leave a message with more information if the PR author is a first-timer
contributors = github.api.contributors(REPO_FULL_NAME).map(&:login)
markdown(WELCOME_MESSAGE) unless contributors.include?(github.pr_author)

# Let the author know how close they are to the PR limit
author_issues = github.api.list_issues(
  REPO_FULL_NAME,
  state: :open,
  assignee: github.pr_author
).length
if author_issues <= PR_LIMIT
  message("You have #{author_issues} PR(s) open of #{PR_LIMIT} allowed")
else
  slow_down_message = <<~MESSAGE
    You have more than #{PR_LIMIT} PRs open! Please wait until
    some have been merged to open more.
  MESSAGE
  warn(slow_down_message)
end
